dist: xenial
language: python
python: 3.7
# 使用python下载已发布的hugo安装更快

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https

  # install - install any dependencies required
install:
  # install latest hugo release version
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - rm -rf public 2> /dev/null

#在travis-ci.com上配置3个环境变量,其中GITHUB_TOKEN是在github.com的 Settings >Developer settings>Personal access tokens里面生成. 
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email bb.qnyd@gmail.com
  - git config --global user.name 7ym0n

script:
  - hugo -d ./dist/

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - cd dist
  - echo "www.scanbuf.net" >> CNAME
  - git init
  - git remote add origin https://7ym0n:1169c202504dc75f220368a35eef6bf9a0064280@github.com/7ym0n/7ym0n.github.io.git
  - git add .
  - git commit -m "${MESSAGE}"
  - git push origin master -f
