#+TITLE: 编辑技巧 - 如何自定义编辑器
#+AUTHOR:
#+DATE: 2021-04-16
#+HUGO_CUSTOM_FRONT_MATTER: :author "7ym0n"
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: post/manual
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: Emacs 编辑器 编辑技巧
#+HUGO_CATEGORIES: Emacs 编辑器 编辑技巧
#+HUGO_DRAFT: false
#+HUGO_TOC: true
* 编辑技巧
使用一些技巧，在编辑文本的过程中，更有效率，比如快速替换，快速选择，多行同时编辑等。
** 需求
- 快速修改特定的字符串
- 快速改变英文字符串大小写
- 修改当前文件名
- 快速移动当前文件
- 快速打开配置文件
- 代码块缩进跟随
- 代码块移动
- 快速跳转
- 自动重新加载
- 文件内容对比
- 符号自动配对
- 插入时删除选择
- 撤销管理
- 高亮光标所在符号字符
- 优化行首跳转
- 高亮光标位置
* 解决方案
*** multiple-cursors
针对多行，多光标编辑，批量修改字符串等，主要应对，在不同的位置不错相同的内容。它可以补充 ~iedit~ 的缺点，进行多光标编辑。
实际上它本身包括了 ~iedit~ 的所有功能，但是对选择标记没有高亮，所以，在正常情况下，使用 ~iedit~ 更多一些，特别是批量修改内容
时。只有在对不同位置进行编辑时使用 ~multiple-cursors~ 。
*** iedit
同时编辑相同的地方。在做代码重构的过程中经常使用的技巧，原来需要多次编辑的地方，可以一次选择标记高亮显示进行编辑。缺点，
无法进行多光标编辑，比如在多行不同位置插入相同的文本内容时，它无法完成。
*** expand-region
扩展标记选择，对标记的内容进行扩展，收缩。有时候选择少了，可以使用它进行扩展标记，选择多了就收缩选择范围。
*** selected
对选择的区域进行快速编辑的快捷键绑定，比如标记一个字符串，那么可以通过简单的快捷键进行修改编辑。
*** undo-tree
撤销管理，显示一个编辑点的树，可以通过上下左右方向键进行快速撤销到某一个编辑点，很直观的显示，让撤销恢复变得可视化，不容
易出错。
*** delsel
在插入数据时，删除标记选择。
*** elec-pair
自动匹配括号的后半部分。
*** ediff
快速对比两个文件的差异，支持多个文件对比，比如对不同版本的文件进行对比差异性。
*** hungry-delete
删除光标前后多余的空格。
*** autorevert
自动重新加载被外部程序修改的文件。
*** drag-stuff
快速移动代码块，支持行，字，标记内容等。
*** flyspell
拼写检查。
*** rainbow-mode
颜色显示，经常在编辑 ~css~ 等文件时，想要显示颜色时使用。
*** kurecolor
颜色编辑工具，配合 ~rainbow-mode~ 使用。
*** aggressive-indent
编辑代码时，自动缩进，特别是修改代码结构时非常有用，代码编辑缩进跟随当前。
*** anzu
搜索替换时，自动标记高亮匹配的内容。能快速识别匹配的内容。
*** beacon
高亮鼠标所在行，一个长长的尾巴，这样能快速的看到光标所在位置。
*** hl-todo
高亮 ~TODO~ 关键字，容易识别那些需要接下来做的事情。
*** symbol-overlay
标记高亮显示。
*** avy
快速跳转，可以通过字符，字等快速跳转到某行。
*** mwim
快速跳转行首尾，包括注释。避免跳转行尾时直接跑到注释后面。必须按两次才到最后一个字符。
*** goto-chg
快速跳转到最后编辑的位置。
*** goto-last-point
快速跳转到光标的最后位置。
*** dumb-jump
代码定义跳转。
*** origami
代码块隐藏/显示。
*** focus
聚焦光标位置，写作或者编写代码时用起来舒服，专注当前编辑。


* 实现代码
#+begin_src emacs-lisp :tangle yes

#+end_src
